Repository mcci-catena/Catena-Sketches, pull requests merged in 2019-05, with the labels that each got.

#78 Fix #77: failures don't necessarily shut things down
  catena4450m101_sensor/catena4450m101_sensor.ino
  catena4450m102_pond/catena4450m102_pond.ino
  catena4450m102_waterlevel/catena4450m102_waterlevel.ino
  catena4460_aqi/catena4460_aqi.ino
  catena4460_bsec_ulp/catena4460_bsec_ulp.ino
  catena4551_test01/catena4551_test01.ino
  catena4612_simple/catena4612_simple.ino
  catena461x_test01/catena461x_test01.ino
Labels: bug, enhancement

#82 Fix #80: missing default value
  catena4450m102_pond/catena4450m102_pond.ino
  catena4450m102_waterlevel/catena4450m102_waterlevel.ino
  catena4460_aqi/catena4460_aqi.ino
  catena4460_bsec_ulp/catena4460_bsec_ulp.ino
  catena4551_test01/catena4551_test01.ino
  catena4612_simple/catena4612_simple.ino
  catena461x_test01/catena461x_test01.ino
Labels: bug

#79 Fix #69: Updated the sketch 'catena4460_bsec_ulp' to support latest BSEC library
  catena4460_bsec_ulp/README.md
  catena4460_bsec_ulp/catena4460_bsec_ulp.ino
Labels: enhancement
